# Workflow for an existing local repository that is synchronized with a remote repository on Github

## Only one branch: main
### Solo work 
#### Repository that was not synchronized and not updated using a proper Git wrokflow
##### Part 1: Verify that the local repository is connected to Github, and the structure of the repository
1.  Check that the local repository is connected to Github:

    `git remote -v`

    If it is connected, we need to see an output:

    origin <https://github.com/monikavila/Github.git> (fetch)

    origin <https://github.com/monikavila/Github.git> (push)

2. Check the current branch 

    `git branch` 


##### Part 2: Update repository locally and remotelly 

1. Check status 
    `git status` 

2. Commit local changes 

    `git add .` 
    `git commit -m "Updating all the changes in one"`

    Note: Ideally, one should commit each change separately to have meaningful commit messages.

3. Pull changes 

    ` git pull`

4. Push changes 
    `git push`


#### Repository that is constantly synchronized 
#####  Update repository locally and remotelly 

1. Check status 
    `git status` 

2. Commit local changes 

    `git add .` 
    `git commit -m "Updating all the changes in one"`

    Note: Ideally, one should commit each change separately to have meaningful commit messages.

3. Pull changes 

    ` git pull`

4. Push changes 
    `git push`


### Team work 
#### Repository that was not synchronized and not updated using a proper Git wrokflow
##### Part 1: Verify that the local repository is connected to Github, and the structure of the repository
1.  Check that the local repository is connected to Github:

    `git remote -v`

    If it is connected, we need to see an output:

    origin <https://github.com/monikavila/Github.git> (fetch)

    origin <https://github.com/monikavila/Github.git> (push)

2. Check the current branch 

    `git branch` 


##### Part 2: Update repository locally and remotelly 

1. Check status 
    `git status` 

2. Pull changes 

    ` git pull`


3. Commit local changes 

    `git add .` 
    `git commit -m "Updating all the changes in one"`

    Note: Ideally, one should commit each change separately to have meaningful commit messages.


4. Push changes 
    `git push`


#### Repository that is constantly synchronized 
#####  Update repository locally and remotelly 

1. Check status 
    `git status` 

2. Pull changes 

    ` git pull`


3. Commit local changes 

    `git add .` 
    `git commit -m "Updating all the changes in one"`

    Note: Ideally, one should commit each change separately to have meaningful commit messages.


4. Push changes 
    `git push`

## Several branches
### Option 1: You first updated the main brannch using the workflow as the repository had only the main branch, and then you realize there are more branches
#### The other branch is contained in the main branch
1. List all branches `git branch -a`

2. Check the commits that the other branches have and that main does not have 
    `git log --oneline --graph main..otherbranch`
    If you do not get any output, then it means that the other branch does not have any commit that it not in the main branch. 

3. Check the commits that main has and the other bramches do not have
    `git log --online --graph otherbranch..main`

4. Confirm the differences between main and other branches
    `git diff -stat main..otherbranch`

    `git diff -stat otherbranch..main`

    The differences are shown because we compare the files between different commits. 

5. Now, let's verify the last common commit between main and the other branch

    `git merge-base main otherbranch`

6. Now, let's verify the tip of the other branch
    
    `git rev-parse otherbranch`

If they are equal, the other branch is fully contained into the main one and it can be safey deleted. 

7. Delete the branch 
    `git branch -d otherbranch`

8. Push the changes = delete remotely
    `git push origin --delete otherbranch`