# Creating a new repository in Git and Github

1.  Navigate to the direcory that will host the local repository.

2.  In the terminal tab `git init -b main`

3.  Add a gitignore file using `touch .gitignore`

4.  Stage files added to the repo `git add .`

5.  Commit the files `git commit -m "Initial commit"`

6.  Create a GitHub repository using on GitHub without README and .gitignore files.

7.  Link the local repository to the remote repository using `git remote add origin URL_GITHUB_REPOSITORY_TO_LINK`

8.  Verify that the remote was set up correctly using `git remote -v`

9.  Push the changes in the local repository to the remote one by running the comand `git push -u origin main`

10. Verify that your local branch is up to date with the remote one by `git fetch` `git status`

11. To create a new branch `git checkout -b NAME_NEW_BRANCH`

12. To push the local branch to the remote `git push -u origin NAME_NEW_BRANCH`

13. To pull the remote branch to the local one -u origin

14. Merge branches in Github using Pull Requests.

15. To delete a local branch use `git branch -d NAME_BRANCH`